name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump patch version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

  build-and-release:
    needs: version
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Build project
        run: |
          $version = "${{ needs.version.outputs.new_tag }}"
          $version = $version.TrimStart('v')
          cargo build --release --target x86_64-pc-windows-msvc
        env:
          CARGO_PKG_VERSION: $version

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.new_tag }}
          name: Release ${{ needs.version.outputs.new_tag }}
          draft: false
          prerelease: false
          files: |
            target/x86_64-pc-windows-msvc/release/kester.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}